### ISSUE TITLE
handout/resources

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#20]

**Comment by damg70** [comment]
To turn GPS on in iOS compass app:

Settings > privacy > location services 

Make sure compass app is set to "on."

Don't know how it works in android. 

:david

I'm all thumbs over here

**Comment by rcrath** [comment]
I will be back on Oahu later tonight and can devote more brain power to finalizing what the hands-on portion is about but here's the gist:
1. Think of a humanities oriented campus related story that involves a specific site. 
2. Walk to that site, noting latlong coordinates along the way, at points that would generate a logical path if the dots were connected. The iPhone provides latlong via the compass app so long as location services are on. I assume there is something similar built in for android. 
3. At the site, record your story and upload to soundcloud. Android users download the soundcloud app and record directly. iOS users download audiocopy, use voice memo to record story and audiocopy to send it to soundcloud. 
4. Paste latlong series into simple web app which by magic will draw the path on a map --- possibly Google because it has better campus resolution than leaflet/mapbox. 
5. Profit.

**Comment by oksveta** [comment]
Sounds good. From my experience in teaching technology workshops, I think it will be helpful to have some handouts that go over the the mechanics (in some detail) of recording lat long, using soundcloud, etc for folks...especially because they will be dispersed through the campus and we won't necessarily be there to help them out. You never know where people are coming from and somethings that seem obvious to us (i.e. how to record in soundcloud) might prove challenging for some, so how can we prepare for that?

**Comment by rcrath** [comment]
@oksveta , @damg70 and I will get this together early this  week. We will send out a prep email Monday or Tuesday too.

**Comment by rcrath** [comment]
[handout.pdf](https://github.com/digiah/DHGetDown/files/424711/handout.pdf)

@oksveta could you please make copies?
