### ISSUE TITLE
Event Web Page

### ISSUE THREAD

**Issue by oksveta** [digiah/DHGetDown#7]
[Event Web Page](http://digiah.github.io/DHGetDown/index.html)

**Comment by rdbeales** [comment]
We have personal pages provided by we could use for this.

**Comment by rcrath** [comment]
We can do Mirroring/rss feed/event announce/calendar on DAHI too.  @oksveta , let me or @damg70 know if you need anything for web presence from us.

**Comment by rcrath** [comment]
Could also do it on github.io.  I set up a [dummy site](http://digiah.github.io/DHGetDown/) that we could redo with the content in markdown.  no need to use this if you have something easier/better.  Instructions for (re)generating the page are [here](https://pages.github.com/)

**Comment by oksveta** [comment]
thanks, @richrath. I will take a stab at it on github.io first, since I like the idea of having everything in one place. hope to have something basic by the end of next week so we can send the URL with the save the dates.

**Comment by oksveta** [comment]
Making progress on the github page that Rich set up. The skeleton is up now and the URL has been added to the top of the issue.

**Comment by rcrath** [comment]
~~@digiah/dhgetdown please use @rcrath, not @richrath.  I should delete the latter as I don't use it.~~ 
booted the troublemaker.  not the first time that has happened this week. ;^)

**Comment by oksveta** [comment]
@rcrath noted!

**Comment by oksveta** [comment]
hello @damg70 @rdbeales @rcrath -- 

I've finished up the event site, including the registration form. Feedback appreciated! 

I've listed myself as the primary contact person for simplicity's sake. Please let me know if you would like to be added or would rather be the primary contact.

[http://digiah.github.io/DHGetDown/](http://digiah.github.io/DHGetDown/)

**Comment by rcrath** [comment]
Hi @oksveta , 

Thanks! This looks great.  Couple of small things:  
- The form seems like it only accepts hawaii.edu google accounts.  We need to teak the permissions to allow open registration I think, especially since we are touting community relations.  
- Once we have the program in place, maybe we can tweak the bullet pt on the home page that begins with "Learn" to be more specific, as well (of course) filling in the program a little better.  

I like the code of conduct.  I am wondering if we could add a line something to the effect of mindful participation to give a "Do" to go with the "Don'ts"  If this sounds ok to @digiah/dhgetdown I'll edit the code of conduct page to add it.

**Comment by oksveta** [comment]
@rcrath 
- Yes, please go ahead and make the amendment to the CoC.
- The registration thing was an oversight on my part (google@uh defaults to uh only and I didn't notice to change it.) Thanks for catching that!

**Comment by rcrath** [comment]
added mindfulness clause to [CoC](http://digiah.github.io/DHGetDown/coc.html).  Successfully registered.  closing the issue.
